Have MirahezeLogbot insert {{TOC right}} on every edit
miraheze/puppet pull request #1664
Opened 2021-02-26 17:50 UTC by dmehus

Might be a better way to fix this, but if MirahezeLogbot inserts `{{TOC right}}` with every edit, it'll always be at the top of `Tech:Server admin log`

2021-02-26 17:55 UTC, dmehus commented
Meh, I need to work on this a bit. Please **do not merge this yet**

2021-02-26 17:56 UTC, RhinosF1 requested changes
We don't want on every edit. We just need it to fix the position of where it is to be above the new log entry.

2021-02-26 18:00 UTC, dmehus commented
> We don't want on every edit. We just need it to fix the position of where it is to be above the new log entry.

True, and this didn't take into account subsequent SAL log entries on the same calendar day. Should I close this and let you start over?

2021-02-26 18:00 UTC, RhinosF1 commented
> > We don't want on every edit. We just need it to fix the position of where it is to be above the new log entry.
> 
> True, and this didn't take into account subsequent SAL log entries on the same calendar day. Should I close this and let you start over?

Yes

2021-02-26 18:01 UTC, closed without merging

2021-02-26 18:01 UTC, dmehus commented
Will let @RhinosF1 do a new PR for this.

2021-02-27 14:22 UTC, RhinosF1 commented
Created #1667

> Will let @RhinosF1 do a new PR for this.