mwscript: support foreachwikiindblist
miraheze/puppet pull request #1786
Opened 2021-06-14 23:16 UTC by Universal-Omega

There is absolutely no guarantee I did this right at all.

2021-06-17 02:54 UTC, Universal-Omega commented
I tested this and it does seem to work.
```shell
universalomega@test3:~$ python3 ./mwscript showJobs.php all
Will execute:
sudo -u www-data /usr/local/bin/foreachwikiindblist /srv/mediawiki/w/cache/databases.json /srv/mediawiki/w/maintenance/showJobs.php
/usr/local/bin/logsalmsg "sudo -u www-data /usr/local/bin/foreachwikiindblist /srv/mediawiki/w/cache/databases.json /srv/mediawiki/w/maintenance/showJobs.php"
Type 'Y' to confirm:
Aborted!
universalomega@test3:~$ python3 ./mwscript showJobs.php foreachwikiindblist
Will execute:
sudo -u www-data /usr/local/bin/foreachwikiindblist /srv/mediawiki/w/cache/databases.json /srv/mediawiki/w/maintenance/showJobs.php
/usr/local/bin/logsalmsg "sudo -u www-data /usr/local/bin/foreachwikiindblist /srv/mediawiki/w/cache/databases.json /srv/mediawiki/w/maintenance/showJobs.php"
Type 'Y' to confirm:
Aborted!
universalomega@test3:~$ python3 ./mwscript showJobs.php extension
Type the ManageWiki name of the extension or skin: addthis
Will execute:
php /srv/mediawiki/w/extensions/MirahezeMagic/maintenance/generateExtensionDatabaseList.php --wiki=loginwiki --extension=addthis
sudo -u www-data /usr/local/bin/foreachwikiindblist /home/universalomega/addthis.json /srv/mediawiki/w/maintenance/showJobs.php
/usr/local/bin/logsalmsg "sudo -u www-data /usr/local/bin/foreachwikiindblist /home/universalomega/addthis.json /srv/mediawiki/w/maintenance/showJobs.php"
Type 'Y' to confirm:
Aborted!
universalomega@test3:~$ python3 ./mwscript showJobs.php skin
Type the ManageWiki name of the extension or skin: cosmos
Will execute:
php /srv/mediawiki/w/extensions/MirahezeMagic/maintenance/generateExtensionDatabaseList.php --wiki=loginwiki --extension=cosmos
sudo -u www-data /usr/local/bin/foreachwikiindblist /home/universalomega/cosmos.json /srv/mediawiki/w/maintenance/showJobs.php
/usr/local/bin/logsalmsg "sudo -u www-data /usr/local/bin/foreachwikiindblist /home/universalomega/cosmos.json /srv/mediawiki/w/maintenance/showJobs.php"
Type 'Y' to confirm:
Aborted!
```

2021-06-19 15:00 UTC, RhinosF1 requested changes
Cant see the generate mentioned in the will execute section

2021-06-19 15:01 UTC, RhinosF1 approved these changes
I'm blind

2021-06-20 07:00 UTC, Reception123 approved these changes

2021-06-20 07:00 UTC, merged