l10nupdate: move to mwdeploy and avoid I/O starvation
miraheze/puppet pull request #2105
Opened 2021-11-05 16:16 UTC by RhinosF1

2021-11-05 16:23 UTC, RhinosF1 commented on modules/mediawiki/manifests/cron.pp
> -        ensure  => present,
I'll do it from the mediawiki profile.

2021-11-05 16:56 UTC, paladox commented on modules/mediawiki/manifests/init.pp
> +        cron { 'l10n-modern-deploy':
Code style please

2021-11-06 06:27 UTC, Universal-Omega requested changes

2021-11-06 06:27 UTC, Universal-Omega commented on modules/mediawiki/manifests/init.pp
> +        ensure = absent,
Should be `ensure  => absent` (missing `>`)

2021-11-06 15:01 UTC, paladox commented on modules/mediawiki/manifests/init.pp
> +        cron { 'l10n-modern-deploy':
Resolved.

2021-11-06 15:03 UTC, merged