setup new mw* with stunnel & prometheus
miraheze/puppet pull request #2183
Opened 2021-12-30 10:49 UTC by RhinosF1

2021-12-30 15:07 UTC, paladox commented
Note that the old infra and new infra won't interact with each other. So the new infra won't connect to the old puppet server so the old infra won't have the data to generate known host filees using the new vms key/or won't know about them at all.

2021-12-30 15:10 UTC, RhinosF1 commented
> Note that the old infra and new infra won't interact with each other. So the new infra won't connect to the old puppet server so the old infra won't have the data to generate known host filees using the new vms key/or won't know about them at all.

I assume we'll have an icinga-new like last time and we can just downtime the checks from the wrong DC

2022-01-02 00:27 UTC, Universal-Omega requested changes

2022-01-02 00:27 UTC, Universal-Omega commented on modules/base/templates/icinga/nrpe.cfg.erb
> +command[check_stunnel_test111]=/usr/lib/nagios/plugins/check_http -H localhost:8101
test101

2022-01-02 00:27 UTC, Universal-Omega commented on modules/base/templates/icinga/nrpe.cfg.erb
> +command[check_stunnel_mwtask101]=/usr/lib/nagios/plugins/check_http -H localhost:8100
mwtask111

2022-01-02 14:31 UTC, merged