db: don't allow access to testglobal from non test servers
miraheze/puppet pull request #2436
Opened 2022-02-25 11:22 UTC by RhinosF1

This should make it impossible to generate cache for beta on production as there will not be the cw_wikis table.

I can only find that some LoginNotifyJobs were trigged for beta. I'm not quite sure how yet.

2022-03-12 11:48 UTC, JohnFLewis commented
Unable to merge because the specified user does not exist.

2022-03-12 11:50 UTC, RhinosF1 commented
Can it not be created?

2022-03-12 15:48 UTC, JohnFLewis commented
> Can it not be created?

Is that not what this PR is for?

2022-03-12 17:00 UTC, RhinosF1 commented
Where do we define users?

2022-03-12 17:17 UTC, JohnFLewis commented
L3-6 and L37-40 give examples in this file. It would require a new section as well as it’s no longer the wild card user

2022-03-27 16:08 UTC, Universal-Omega commented
Is this actually necessary to even do? I'm not sure I really see the need here. At least I don't see the need if it's to complex to do.

2022-03-27 16:10 UTC, RhinosF1 commented
> Is this actually necessary to even do? I'm not sure I really see the need here. At least I don't see the need if it's to complex to do.

Complex, it's not really at all. It's just super low priority.

Necessary, not really but it's defence in depth. It's nice to close off another area of risk.

2022-05-30 16:04 UTC, Universal-Omega commented
Can we also add a comment here mentioning test101, so when searching for teat101 we can find the IP if it ever needs changed again? Just makes it easier.

2022-05-30 16:08 UTC, RhinosF1 commented
> Can we also add a comment here mentioning test101, so when searching for teat101 we can find the IP if it ever needs changed again? Just makes it easier.

Sure, updated!

2022-05-30 16:30 UTC, Universal-Omega commented
Thanks!

2022-06-25 14:00 UTC, JohnFLewis requested changes

2022-06-25 14:00 UTC, JohnFLewis commented on modules/mariadb/templates/grants/mediawiki-grants.sql.erb
> +GRANT USAGE
Same problem all the way down as well, they need to be their own section as the host param is different.

2022-07-15 07:03 UTC, closed without merging