deploy-mediawiki: add arguments for branch and rebuildLC language
miraheze/puppet pull request #2587
Opened 2022-05-23 21:40 UTC by Universal-Omega

2022-05-23 21:48 UTC, RhinosF1 requested changes

2022-05-23 21:48 UTC, RhinosF1 commented on modules/mediawiki/files/bin/deploy-mediawiki.py
>      if submodules:
Why? I assume you're trying to except False. Use None and type check it to be optional.

2022-05-23 21:48 UTC, RhinosF1 commented on modules/mediawiki/files/bin/deploy-mediawiki.py
> +                branch = False
Use None not False

2022-05-23 21:48 UTC, RhinosF1 commented on modules/mediawiki/files/bin/deploy-mediawiki.py
> +                    stage.append(_construct_git_pull(repo, submodules=sm, branch=branch))
Why not use args.branch directly?

2022-05-23 21:48 UTC, RhinosF1 commented on modules/mediawiki/files/bin/deploy-mediawiki.py
> +                lang = f'--lang={args.lang}'
What happens if it's an invalid language?

2022-05-24 05:53 UTC, RhinosF1 requested changes
Please add tests for new functionality

2022-05-24 06:28 UTC, Universal-Omega commented
> Please add tests for new functionality

Python tests are above my ability at the moment. While I could probably figure it out, I don't feel the need for me to more than I need to for this PR. This PR is supposed to make it easier to pull stuff, and faster to run world when only some stuff needs done (like just English for example). If I have to add python tests everytime I change something to it, I just won't change anything, and will abandon this PR. It is not worth my time. If you really want tests for this, then please submit a PR to my forked branch, or a follow-up PR to this. I'm not interested in learning how to make/update python tests at the moment with to much other things going on in RL for me, and other more pressing issues at Miraheze then that. This PR was supposed to be something simple but making it easier at times to use. I don't want it to be more complicated for me right now, and just don't have time to do that now.

I'm requesting that this review be retracted, and this PR still merged without tests, or that you submit a PR to my fork to add them. Thanks!

2022-05-24 06:31 UTC, RhinosF1 commented
> > Please add tests for new functionality
> 
> Python tests are above my ability at the moment. While I could probably figure it out, I don't feel the need for me to more than I need to for this PR. This PR is supposed to make it easier to pull stuff, and faster to run world when only some stuff needs done (like just English for example). If I have to add python tests everytime I change something to it, I just won't change anything, and will abandon this PR. It is not worth my time. If you really want tests for this, then please submit a PR to my forked branch, or a follow-up PR to this. I'm not interested in learning how to make/update python tests at the moment with to much other things going on in RL for me, and other more pressing issues at Miraheze then that. This PR was supposed to be something simple but making it easier at times to use. I don't want it to be more complicated for me right now, and just don't have time to do that now.

It's about 3 lines for the git changes which is what I care about and yes python tests should be added as much as we can. This is a critical part of our infra. I can happily write them for you but I'm going to block any PR that changes functionality on our team's python scripts without adding tests for the change.
> I'm requesting that this review be retracted, and this PR still merged without tests, or that you submit a PR to my fork to add them. Thanks!

2022-05-24 07:53 UTC, Reception123 commented
A few observations about the comments here:

1) Regarding the mandatory tests for every new functionality, I don't personally think this should be absolutely mandatory. We are quite a small organisation/team and sometimes we need to prioritise functionality over testing. If you believe that testing is very important, then there is nothing stopping you from adding it after / modifying the PR.

2) Regarding the statement "I'm going to block any PR that changes functionality " I think there's a few issues here. The statement seems to imply that a single member of the MW team can simply decide to block a change - I don't think a single member should be able to since we are a collaborative team. Either way, there is clearly a structure with the EM being the one who would be able to 'block' changes, especially in this case since I am the only one who can merge the change from the team. Also an issue is that there is really no policy or agreement about mandating tests, so without a clear rule I don't see why it should just be decided like that unilaterally.

Rather than asking people to do something, it's probably best to do it yourself if you want to see it done. My view however is that without a clear policy/rule, I don't see why this shouldn't be merged and why testing should be prioritized over functionality. If you want  such a rule/policy, that should be discussed with the team, as there is clearly disagreement about the such a rule.
Please do also consider your choice of words which seem to imply that you have more 'power' than other members of the team.

2022-05-24 09:45 UTC, RhinosF1 commented on modules/mediawiki/files/bin/deploy-mediawiki.py
> +        extrap += f'--branch={branch}'
Tests added. Please see output as --recurse-submodules & --branch don't work. That's why we do tests and this method is supposed to be easy to check.

2022-05-24 09:46 UTC, RhinosF1 requested changes
See comments, doesn't work.

2022-05-24 09:46 UTC, RhinosF1 commented
https://github.com/Universal-Omega/puppet/pull/7/files

2022-05-24 10:14 UTC, RhinosF1 commented on .github/pythonchecks.txt
>  requests==2.27.1
This doesn't exist in Debian. We'll need to somehow install it on the appservers via puppet.

2022-05-24 16:56 UTC, RhinosF1 requested changes
1 question, 1 to do for any point & 1 I assume you'll want me to do.

2022-05-24 16:56 UTC, RhinosF1 commented on modules/mediawiki/files/bin/deploy-mediawiki.py
> +            rebuild.append(f'sudo -u www-data php /srv/mediawiki/w/maintenance/rebuildLocalisationCache.php {lang} --quiet --wiki={envinfo["wikidbname"]}')
We should probably split this off into a generate method. Should I do a pull request for that?

2022-05-24 16:56 UTC, RhinosF1 commented on modules/mediawiki/manifests/deploy.pp
> +        'langcodes',
Is there any way to pin this?

2022-05-24 16:56 UTC, RhinosF1 commented on modules/mediawiki/files/bin/deploy-mediawiki.py
>      return f'sudo -u {DEPLOYUSER} git -C {_get_staging_path(repo)} pull {extrap} --quiet'
Note to self: make this method more extendable. It's going to be rubbish if we need to account for double spaces for every command in tests.

2022-05-29 05:52 UTC, Reception123 approved these changes

2022-05-29 05:52 UTC, merged

2022-05-30 10:31 UTC, RhinosF1 commented
I filed https://phabricator.miraheze.org/T9310 as a follow up