ssl-acme: skip checking the host key
miraheze/puppet pull request #2645
Opened 2022-06-02 22:18 UTC by MacFan4000

if we don't skip it then the auto-renewal script fails

2022-06-03 16:08 UTC, RhinosF1 requested changes
You need to find where to place the key and add it.

2022-06-03 18:17 UTC, MacFan4000 commented
> You need to find where to place the key and add it.

If you mean add it server side (not in puppet) it’s not possible for me to do that as my access is very limited.

This is a simple solution that skips the check just for this script.

2022-06-03 18:25 UTC, RhinosF1 commented
This might be simple but it's also dangerous and poses security implications. Not really bothered whether it's done in puppet or on server.

2022-06-04 07:42 UTC, Universal-Omega commented
This has security risk to do also.

2022-06-19 02:45 UTC, closed without merging