allow direct pushing of certs to GitHub T7582
miraheze/puppet pull request #2996
Opened 2022-11-11 13:08 UTC by Reception123

Do not merge! It can probably be improved but this should likely work

2022-11-11 22:34 UTC, MacFan4000 requested changes
These suggestions fix the broken CI

2022-11-11 22:34 UTC, MacFan4000 commented on modules/ssl/files/ssl-certificate.py
> +        os.system(f'git config --global core.sshCommand "ssh -i /var/lib/nagios/id_rsa -F /dev/null -o ProxyCommand=\'nc -6 -X connect -x bast.miraheze.org:8080 %h %p\'"')
```suggestion
        os.system('git config --global core.sshCommand "ssh -i /var/lib/nagios/id_rsa -F /dev/null -o ProxyCommand=\'nc -6 -X connect -x bast.miraheze.org:8080 %h %p\'"')
```

2022-11-11 22:34 UTC, MacFan4000 commented on modules/ssl/files/ssl-certificate.py
> +        os.system(f'git -C /srv/ssl/ssl/ config user.email "noreply@miraheze.org" &&   git -C /srv/ssl/ssl/ config user.name "MirahezeSSLBot"')
```suggestion
        os.system('git -C /srv/ssl/ssl/ config user.email "noreply@miraheze.org" &&   git -C /srv/ssl/ssl/ config user.name "MirahezeSSLBot"')
```

2022-11-11 22:34 UTC, MacFan4000 commented on modules/ssl/files/ssl-certificate.py
> +        os.system(f'echo \'{self.domain}:\' >> /srv/ssl/ssl/certs.yaml')
```suggestion
        os.system(f"echo '{self.domain}:' >> /srv/ssl/ssl/certs.yaml")
```

2022-11-11 22:34 UTC, MacFan4000 commented on modules/ssl/files/ssl-certificate.py
> +        os.system(f'echo \'\t url: \'{self.domain}\' \' >> /srv/ssl/ssl/certs.yaml')
```suggestion
        os.system(f"echo '\t url: '{self.domain}' ' >> /srv/ssl/ssl/certs.yaml")
```

2022-11-11 22:34 UTC, MacFan4000 commented on modules/ssl/files/ssl-certificate.py
> +        os.system(f'echo \'\t ca: \'LetsEncrypt\' \' >> /srv/ssl/ssl/certs.yaml')
```suggestion
        os.system("echo '\t ca: 'LetsEncrypt' ' >> /srv/ssl/ssl/certs.yaml")
```

2022-11-11 22:34 UTC, MacFan4000 commented on modules/ssl/files/ssl-certificate.py
> +        os.system(f'echo \'\t disable-event: \'false\' \n \' >> /home/reception/certs.yaml')
```suggestion
        os.system("echo '\t disable-event: 'false' \n ' >> /home/reception/certs.yaml")
```

2022-11-11 22:34 UTC, MacFan4000 commented on modules/ssl/files/ssl-certificate.py
> +        os.system(f'git -C /srv/ssl/ssl/ add /srv/ssl/ssl/certs.yaml')
```suggestion
        os.system('git -C /srv/ssl/ssl/ add /srv/ssl/ssl/certs.yaml')
```

2022-11-11 22:34 UTC, MacFan4000 commented on modules/ssl/files/ssl-certificate.py
> +        os.system(f'git -C /srv/ssl/ssl/ push origin master')
```suggestion
        os.system('git -C /srv/ssl/ssl/ push origin master')
```

2022-11-12 11:11 UTC, Reception123 commented
After discussing with @Universal-Omega I'll leave it to him to correct the issues as he wants to make some other improvements as well.

2022-11-14 21:45 UTC, Universal-Omega commented on modules/ssl/files/ssl-certificate.py
> +        os.system(f'git config --global core.sshCommand "ssh -i /var/lib/nagios/id_rsa -F /dev/null -o ProxyCommand=\'nc -6 -X connect -x bast.miraheze.org:8080 %h %p\'"')
Done.

2022-11-14 21:45 UTC, Universal-Omega commented on modules/ssl/files/ssl-certificate.py
> +        os.system(f'echo \'{self.domain}:\' >> /srv/ssl/ssl/certs.yaml')
Done.

2022-11-14 21:45 UTC, Universal-Omega commented on modules/ssl/files/ssl-certificate.py
> +        os.system(f'echo \'\t ca: \'LetsEncrypt\' \' >> /srv/ssl/ssl/certs.yaml')
Done.

2022-11-14 21:45 UTC, Universal-Omega commented on modules/ssl/files/ssl-certificate.py
> +        os.system(f'git -C /srv/ssl/ssl/ add /srv/ssl/ssl/certs.yaml')
Done.

2022-11-14 21:46 UTC, Universal-Omega commented on modules/ssl/files/ssl-certificate.py
> +        os.system(f'git -C /srv/ssl/ssl/ push origin master')
Done.

2022-11-14 21:46 UTC, Universal-Omega commented on modules/ssl/files/ssl-certificate.py
> +        os.system(f'echo \'\t disable-event: \'false\' \n \' >> /home/reception/certs.yaml')
Done.

2022-11-14 21:46 UTC, Universal-Omega commented on modules/ssl/files/ssl-certificate.py
> +        os.system(f'echo \'\t url: \'{self.domain}\' \' >> /srv/ssl/ssl/certs.yaml')
Done.

2022-11-14 21:46 UTC, Universal-Omega commented on modules/ssl/files/ssl-certificate.py
> +        os.system(f'git -C /srv/ssl/ssl/ config user.email "noreply@miraheze.org" &&   git -C /srv/ssl/ssl/ config user.name "MirahezeSSLBot"')
Done.

2022-11-26 10:35 UTC, Reception123 commented
The new changes replace everything in certs.yaml with the new wiki (so removes all the contents) - see https://github.com/miraheze/ssl/commit/cd54c7cdcb9e410aae42325ab55515a993da8148

2022-11-26 16:51 UTC, Universal-Omega commented
> The new changes replace everything in certs.yaml with the new wiki (so removes all the contents) - see [miraheze/ssl@cd54c7c](https://github.com/miraheze/ssl/commit/cd54c7cdcb9e410aae42325ab55515a993da8148)

That is fixed now.

2022-11-26 19:01 UTC, Universal-Omega approved these changes

2022-11-26 19:01 UTC, merged