check_reverse_dns: don't force mw-lb.miraheze.org
miraheze/puppet pull request #3281
Opened 2023-07-09 14:35 UTC by MacFan4000

There is no technical reason that a custom domain couldn't point to some other miraheze.org subdomain. All possible subdomains will always exist and resolve to our servers. This uses regex to ensure that the CNAME is of the format <subdomain>.miraheze.org . The alert really comes into play if somebody has changed their DNS after the domain was setup for their wiki. And if they just changed what subdomain the record points to, I don't think it's worth chasing the user up about it. As for new domains, I always check the records beforehand (and anybody else handling SSL requests should too), and thus this check should not be relied on when adding SSL certs. We should be checking records before adding SSL, and only contacting users after if they changed it after, and for some reason the new configuration won't work. (non-miraheze.org CNAME, or improper A records, or somthing similar, or not pointed at all)

2023-07-09 17:21 UTC, MacFan4000 commented
updated to disallow cp* and non-mediawiki subdomains (most) and non-mw subdomains not included, and other server names would already fail the RDNS check. (the left out non-mw subdomains are the ones not going though varnish)

2023-07-09 18:53 UTC, RhinosF1 commented
It would be nice to see tests

2023-08-13 05:01 UTC, paladox commented on modules/monitoring/files/check_reverse_dns.py
> +        re.match("[A-Za-z]+.miraheze.org", cname) and
Subdomains can contain numbers.

2024-02-01 19:10 UTC, Universal-Omega requested changes

2024-02-01 19:10 UTC, Universal-Omega commented on modules/monitoring/files/check_reverse_dns.py
> +        not re.match("cp[1-9][0-9]*\.miraheze\.org", cname) and
I don't think we need this since hostnames use wikitide.net now

2024-02-01 19:10 UTC, Universal-Omega commented on modules/monitoring/files/check_reverse_dns.py
> +        not re.match("(webmail|phabricator|grafana|icinga|matomo|static|donate|reports)\.miraheze\.org", cname)
Remove webmail

2024-02-01 19:23 UTC, MacFan4000 commented
> It would be nice to see tests

With the change a bit simpler now, I don’t think additional tests are needed.

2024-02-01 19:23 UTC, RhinosF1 commented
> > It would be nice to see tests
> 
> With the change a bit simpler now, I don’t think additional tests are needed.

Tests are always good. This is one of the early targets for Python functions so I'll write them.

2024-03-14 00:23 UTC, merged