Update rename-wiki.py
miraheze/puppet pull request #3589
Opened 2024-01-07 15:11 UTC by RhinosF1

2024-01-07 21:37 UTC, Reception123 commented on modules/mediawiki/files/cookbooks/rename-wiki.py
> +    command = generate_salt_command('db131*', f'cmd.run "mysql -e \'SELECT wiki_dbcluster FROM mhglobal.cw_wikis WHERE wiki_dbname = "{oldwiki_db}" \' "')
I think this should be:
command = generate_salt_command('db131*', f'cmd.run \'mysql -e "SELECT wiki_dbcluster FROM mhglobal.cw_wikis WHERE wiki_dbname = \'{oldwiki_db}\'" \'')

2024-01-08 13:33 UTC, Reception123 commented
I've tried various things but it seems python/salt don't like escaping. We could potentially replace the SQL with a RemoteWiki getDBcluster but that would need a script.

2024-02-03 04:36 UTC, Universal-Omega requested changes

2024-02-03 04:36 UTC, Universal-Omega commented on modules/mediawiki/files/cookbooks/rename-wiki.py
> +    execute_salt_command(salt_command=generate_salt_command('mwtask141', f'sudo -u www-data php /srv/mediawiki/w/extensions/CreateWiki/maintenance/renameWiki.php --wiki=loginwiki --rename {oldwiki_db
Nerds to support multiversion and use mwtask181

2024-02-03 04:36 UTC, Universal-Omega commented on modules/mediawiki/files/cookbooks/rename-wiki.py
>      'c3': 'db142',
update clusters

2024-02-03 04:36 UTC, Universal-Omega commented on modules/mediawiki/files/cookbooks/rename-wiki.py
> +    command = generate_salt_command('db131*', f'cmd.run "mysql -e \'SELECT wiki_dbcluster FROM mhglobal.cw_wikis WHERE wiki_dbname = "{oldwiki_db}" \' "')
Update server

2024-03-17 06:30 UTC, Universal-Omega approved these changes

2024-03-17 06:30 UTC, merged